#!/bin/sh

if [ -z "$1" ]
then
	echo "Please provide version as first paratemer"
	exit 1
fi

# Update version in plugin.xml
sed -E -e 'H;1h;$!d;x' -e 's@version\=\"[^"\s]*\"@version="'$1'"@' -i '' plugin.xml

# Update version in package.json
npm --no-git-tag-version --force version $1

# Update version in README.md
# It bumps version number in the following line : `$ cordova plugin add com-infobip-plugins-mobilemessaging#0.8.5 --save`
sed -E -e 'H;1h;$!d;x' -e 's@com-infobip-plugins-mobilemessaging#.*\-\-save@com-infobip-plugins-mobilemessaging#'$1' \-\-save@' -i '' README.md

if [ -z "$2" ]
then
	git add plugin.xml
	git add package.json
	git add README.md
else
	echo "Skipping 'git add'"
fi
